### ISSUE TITLE
Unable to get SAML token from ADFS IdP

### ISSUE THREAD

**Issue by pashtika** [vdenotaris/spring-boot-security-saml-sample#10]
It seems that Authentication object does not returning SAML assertion token? We're unable to find it out from the API use for SAML

Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
SAMLCredential credential = (SAMLCredential) authentication.getCredentials();
pageContext.setAttribute("authentication", authentication);
pageContext.setAttribute("credential", credential); 

Could you please let us know how to get token?

**Comment by vdenotaris** [comment]
For any questions, please, use [StackOverflow](http://stackoverflow.com/questions/tagged/spring-saml). Cheers, Vi.
