### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by larry13767** [vdenotaris/spring-boot-security-saml-sample#11]
In both firefox and safari, going to localhost:8080 fails with the following message:

"Too many redirects occurred trying to open "http://localhost:8080/saml/discovery?entityID=com%3Avdenotaris%3Aspring%3Asp&returnIDParam=idp". This might occur if you open a page that is redirected to another page which is then directed to open the original page.

**Comment by vdenotaris** [comment]
Hi. I will try to replicate the reported issue as soon as possible, in order to give you a feedback and, just in case, a solution/patch.

**Comment by larry13767** [comment]
Thank you very much for your attention

**Comment by vdenotaris** [comment]
Sprry for the late answer, I was out and without the possibility to check the issue.
I tried to replicated the error, but the project still works fine (there is only an advertisement on Google Chrome for using a non-secure form). Probably, your issue depends about a custom configuration, some networking setting of something similar. Anyway, if you will provide me other information, I could try to check once again.

Best regards, Vincenzo.

**Comment by jlsalmon** [comment]
I came across the same issue, and solved it by clearing my browser cookies. In Chrome, the easiest way to do this is to open a new incognito window.

**Comment by pcnoic** [comment]
The issue still exists even with incognito.

**Comment by vdenotaris** [comment]
According to the triage, this issue is not reproducible for the as-is project.
