### ISSUE TITLE
Duplicate package "controllers" / "contollers"

### ISSUE THREAD

**Issue by elygre** [vdenotaris/spring-boot-security-saml-sample#15]
As seen in https://github.com/vdenotaris/spring-boot-security-saml-sample/tree/master/src/main/java/com/vdenotaris/spring/boot/security/saml/web, there are two packages with the almost same name: controllers and contolles (missing the R). They both contain the same Controllers, so this is probably a simple copy/paste bug.

**Comment by vdenotaris** [comment]
Yes, you are right :)
I will fix it asap.

Thank you so much for reporting the issue.

**Comment by vdenotaris** [comment]
Fixed.
