### ISSUE TITLE
ssocircle: Unable to do Single Sign On or Federation.

### ISSUE THREAD

**Issue by CrossfireCurt** [vdenotaris/spring-boot-security-saml-sample#22]
Hi, I'm very new to SAML so my apologies if this is a stupid question.

I've setup the project locally (localhost:8080) and running it through IntelliJ. I can successfully get to the landing page and select ssocircle as the IdP. Once I'm redirected to ssocircle, I authenticate and then I get the following error:

```
Error occurred

Reason: Unable to do Single Sign On or Federation.

Please enable the additional debug option in "My Debug".
Detailed trace information only available with paid accounts.
Check our plans.
```

The handshake did not complete and my local instance never got any information from ssocircle.

Is this a limitation of my environment? Is this because ssocircle can't talk back to my server? 
Thanks for your help!

**Comment by CrossfireCurt** [comment]
Figured this out. Had to create my own metadata and upload it to ssocircle for my own entityId.

**Comment by hmannam** [comment]
I have created my own SP metadata for my local instance and uploaded. Still getting the same issue. Appreciate your help. Thanks. 

I'd like to add few more detail about my issue. 
I tried to access my local instance. http://localhost:8080/XXX
Click on 'Login' button  on this page which should redirect to sso circle login page. But got below issue,
**No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.**
Then from chrome developer tools, i have copied the url that has 'SAMLRequest' in it and pasted it in the browser and it got redirected to sso login page as expected. once I login i see the message as,
**Error occurred

Reason: Unable to do Single Sign On or Federation.

Please enable the additional debug option in "My Debug".
Detailed trace information only available with paid accounts.
Check our plans.**

Not sure whether it is a time out issue because of manual copy paste i did?

Any help on xmlhttprequest issue is highly appreciated. Thanks once again.

- Haritha.

**Comment by CrossfireCurt** [comment]
@hmannam you cannot invoke the login handshake via AJAX/XMLHTTPRequest.

**Comment by hmannam** [comment]
thanks for your reply, Curt. Any other ideas on how to do the login handshake?

**Comment by CrossfireCurt** [comment]
Yes, redirect the browser. Have you tried standing up the example and trying it there? The example project works very well.

**Comment by hmannam** [comment]
I haven't tried the example. Looks like this is an example of spring saml extension. I am using OpenSAML library to implement the Service Provider. But I will give it a try it should definitely be helpful to some extent.

**Comment by CrossfireCurt** [comment]
You are asking questions about something that has nothing to do with this project.

**Comment by suvarnajayanth** [comment]
Hi CrossfireCurt
Even am getting same error ''
`Error occurred

Reason: Unable to do Single Sign On or Federation.

Please enable the additional debug option in "My Debug".
Detailed trace information only available with paid accounts.
Check our plans.`

I did not clear on your second post 

'Figured this out. Had to create my own metadata and upload it to ssocircle for my own entityId.'

I created metadata by using the url : saml/metadata , and uploaded , still its not working , could you please help me ?

**Comment by CrossfireCurt** [comment]
@suvarnajayanth how am I supposed to help you if you don't supply any details?

**Comment by raymond4ca** [comment]
I have the same issue. I created a new metadata with new entityID, but it still doesn't work.

**Comment by hookhead** [comment]
Hi Vincenzo,

This isn't really an issue, but more of a question...

I have downloaded your code and have got it working quite easily.  Thank you.  

I am now trying to integrate it into an existing project.  For simplicity, for the moment I am still using SSOCircle and the same SP Entity ID.

The existing project uses an applicationContext.xml file, so there was a little bit of tweaking involved.  I had to add the following to the applicationContext.xml as configure(HttpSecurity http) wasn't been called (non-Spring boot environment I guess?).  

`   <context:component-scan base-package="com.mycompany.security.sso.saml"/>

    <http entry-point-ref="samlEntryPoint" pattern="/saml/**">
        <intercept-url pattern="/saml/**" access=".../>
        <http-basic />
        <custom-filter before="CHANNEL_FILTER" ref="metadataGeneratorFilter"/>
        <custom-filter after="BASIC_AUTH_FILTER" ref="samlFilter"/>
        <custom-filter before="CSRF_FILTER" ref="samlFilter"/>
    </http>
`

This seems to work to a degree, but when I do the discovery I get the same error as the guys above.

I am surprised, as your sample code is still working perfectly and I am using effectively the same code, service provider id etc., with the exception that I am using an applicationContext.xml. 

What are the most common reasons for getting this error, and given that your code is still working and mine is failing, while using SSO Circle, the same SP Entity ID, etc., do you have any idea what I may be doing wrong?

Many thanks in advance,
Mark

**Comment by supernicky22** [comment]
Hi everybody, as I do not find out how to place my question elsewhere (in stackoverflow I am not allowed to place questions yet).

I have 2 applications with as I think exactly the same SAMLWebSecurityConfigurerAdapter. As I am puzzling around with the SAML for some days now, the metadata creation is still containing the vdnotaris. One of the apps works  fine: I start it, get to ssocircle, log on or click on "I am not a robot", am routed back, fine. The second one gives me the error after logging on or after the robot-check. Why? Any hint would really be appreciated. Thanks a lot.
