### ISSUE TITLE
kindly provide instructions on enabling ECP

### ISSUE THREAD

**Issue by avinash92c** [vdenotaris/spring-boot-security-saml-sample#24]
Hi,
 i have been trying a few samples on your library, and i have got stuck with ECP configuration for quite a while.
Would be very helpful if you could provide some insight into resolving this.

i've made ecp configurations as below 
```
 @Bean
    public ExtendedMetadata extendedMetadata() {
        ExtendedMetadata extendedMetadata = new ExtendedMetadata();
        extendedMetadata.setIdpDiscoveryEnabled(true);
//      extendedMetadata.setSignMetadata(false);
        extendedMetadata.setEcpEnabled(true);
        return extendedMetadata;
    }
```

```
 @Bean
    public MetadataGenerator metadataGenerator() {
        MetadataGenerator metadataGenerator = new MetadataGenerator();
        metadataGenerator.setEntityId("urn_boot_saml");
        metadataGenerator.setExtendedMetadata(extendedMetadata());
        List<String> bindingsSSO = new ArrayList<>();
        bindingsSSO.add("paos");
        bindingsSSO.add("post");
        bindingsSSO.add("artifact");
        metadataGenerator.setBindingsSSO(bindingsSSO);
        return metadataGenerator;
    }
```

i keep getting the below when i try to curl the paos endpoint

`curl -k -I -H 'Accept: application/vnd.paos+xml' -H 'PAOS: ver="urn:liberty:paos:2003-08";"urn:oasis:names:tc:SAML:2.0:profiles:SSO:ecp"' https://localhost:8443/saml/sso`

```
HTTP/1.1 406 Not Acceptable
Date: Fri, 29 Jul 2016 09:46:11 GMT
X-Application-Context: application:8443
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Pragma: no-cache
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
Content-Type: text/html; charset=ISO-8859-1
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 299
Server: Jetty(9.2.16.v20160414)
```

complete details in below link.
[stackoverflow post](http://stackoverflow.com/questions/38656933/springboot-security-sso-ecp-configuration)

**Comment by vdenotaris** [comment]
Hi,

Your ECP configuration seems to be fine, but the request doesn't look well-formed: for instance, not even an IdP endpoint is specified, user credentials as well.
Furthermore, ECP is not always supported by third-party IdPs. For this reason, this feature is not currently covered by this sample project. I will consider this scenario for a future release.

Thanks for your understanding,
Cheers, V.
