### ISSUE TITLE
saml sample will not authenticate for any port but 8080

### ISSUE THREAD

**Issue by EvilJinious1** [vdenotaris/spring-boot-security-saml-sample#35]
I modify the spring port server port to 9800 (and I tried others) and i get an error from sso circle.

But if I change it back to 8080 then it works fine.  Is there any reason that only port 8080 works with your example?

Also I tried to change the context path from "/" to "myservice" and that seemed to fail as well.

In all cases, I created a brand new user.  But if I use localhost:8080/ then all is fine.

Is this some weird limitation of sso circle or is there some hidden configuration that I am missing?

**Comment by vdenotaris** [comment]
The application is pre-registered on SSO Circle, with localhost:8080 as endpoint (static).
If you would like to use another port, you need to:

* change the default EntityId
* make a brand-new registration on SSO Circle (or any other IdP) 

This is then not an issue, but an expected behaviour.

**Comment by dannygoncalves** [comment]
Old thread, but I got here for the same thing, I know it's not a bug @vdenotaris 

how do I change the default EntityId? where in the project?
