### ISSUE TITLE
Cannot set AssertionConsumerServiceIndex with AuthnRequest

### ISSUE THREAD

**Issue by kasunchandrasiri** [vdenotaris/spring-boot-security-saml-sample#39]
Try to set  AssertionConsumerServiceIndex using org.springframework.security.saml.websso.WebSSOProfileOptions#setAssertionConsumerIndex method.
But its not append to the AuthnRequest.

**Comment by kasunchandrasiri** [comment]
Hi Vincenzo,
Can you direct me to resolve this?
Cheers

**Comment by vdenotaris** [comment]
Custom configurations are not in the scope of this project.
