### ISSUE TITLE
Is a default LogoutFilter needed?

### ISSUE THREAD

**Issue by FlasH-RUS** [vdenotaris/spring-boot-security-saml-sample#41]
Hi,
First, thanks for this sample :)
Second, I have a question (that may resolve into an actual issue).
Why does your [WebSecurityConfig](https://github.com/vdenotaris/spring-boot-security-saml-sample/blob/master/src/main/java/com/vdenotaris/spring/boot/security/saml/web/config/WebSecurityConfig.java#L524) contain a default Spring LogoutFilter configuration:
```
        http
            .logout()
                .logoutSuccessUrl("/");
```
From what I understand after hours spent on making Spring SAML work correctly, it (Spring SAML) overrides the default logout behavior with its own (available at /saml/logout), therefore the default Spring _LogoutFilter_ doesn't make sense anymore (it's still available by POST to /logout, but it literally does nothing except for redirecting to /). So since _LogoutConfigurer_ comes as a default and _WebSecurityConfig_ uses defaults (by reusing a default constructor which in turn calls `this(false)`), does it makes sense to replace the snippet above with `http.logout.disable();` at least to avoid confusion?

**Comment by vdenotaris** [comment]
You suggestion is absolutely right. This issue will be fixed in the next release.
Thanks a lot for your contribution. 👍
