### ISSUE TITLE
Missing update-certifcate.sh

### ISSUE THREAD

**Issue by harishkannarao** [vdenotaris/spring-boot-security-saml-sample#43]
Hi,
When I run the application in local, I get 

**javax.net.ssl.SSLPeerUnverifiedException: SSL peer failed hostname validation for name: null**

As per the read me, I need to update the certificate, however update-certifcate.sh is not available in the repository.

Please add the shell script to the repository.

Regards,
Harish

**Comment by vdenotaris** [comment]
Hi,

I tried to replicate the error, but everything seems to look fine: ![screenshot]("https://preview.ibb.co/ibzjaG/Screen_Shot_2017_12_05_at_19_02_22.png")

Could you please post your command history?

Cheers, V.

**Comment by liebig** [comment]
Certificate update works for me also with Windows and Cygwin.
