### ISSUE TITLE
The effect of CSRF on the project

### ISSUE THREAD

**Issue by lushoumei** [vdenotaris/spring-boot-security-saml-sample#44]
We saw that you disabled the csrf in the source, but our project need to avoid the csrf attack, so we cannot disable it. 
When we allow the csrf, the authentication failed, if we disable the csrf like your source, the authentication can success. So we want to know how to solve the problem. can you help us? Thank you very much.

**Comment by vdenotaris** [comment]
Hi,

Please look at @vschafer's answer about the topic on StackOverflow:
 - [Spring SAML Extension and Spring Security CSRF Protection Conflict](https://stackoverflow.com/questions/26508835/spring-saml-extension-and-spring-security-csrf-protection-conflict)

Cheers, V.
