### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Webysther** [vdenotaris/spring-boot-security-saml-sample#45]
Hi, is possible add Dockerfile used in hub.docker inside project? I need change volume and i do no how is created.

Thanks and great job!

**Comment by vdenotaris** [comment]
The Dockerfile will be published in the next release.

**Comment by quetsalkoatl** [comment]
I would appreciate the Dockerfile as well. Our firewall blocks some of the layers with "very high risk" so I can't pull the image.

**Comment by vdenotaris** [comment]
Dockerfile just published within the new release.
