### ISSUE TITLE
How to use https, instead of http

### ISSUE THREAD

**Issue by rohit0903** [vdenotaris/spring-boot-security-saml-sample#53]
I created an OKTA based application using this code. Here, on local system I am able to access the application on http://localhost:8080 and able to authenticate user as well using SSO url as: http://localhost:8080/saml/SSO

**Question:**
How to run our application on https, instead of http ? What my company has provided is https://"domain-name":8080/saml/SSO

**Comment by rohit0903** [comment]
Thanks for the reply. It might be out of scope, but if you can at least give me the direction where to start to enable https would be of great help.

**Comment by chriswhite199** [comment]
Update your application.properties:

    server.port=8443
    server.ssl.key-store=classpath:saml/samlKeystore.jks
    server.ssl.key-store-password=nalle123
    server.ssl.keyStoreType=JKS
    server.ssl.keyAlias=apollo
