### ISSUE TITLE
CSRF Attack Vulnerability if Payload on POST is not form

### ISSUE THREAD

**Issue by pnpninja** [vdenotaris/spring-boot-security-saml-sample#55]
Please change CSRF token on successful response by checking in Cookie or Header sent from User

**Comment by vdenotaris** [comment]
CSRF check is disabled by default in the current version.
However, it is going to be enabled in the next version.
If you would like to take a look at, please refer to the _development_ branch: https://github.com/vdenotaris/spring-boot-security-saml-sample/tree/new/spring5

**Comment by pnpninja** [comment]
Still doesn't work. We need to add a custom filter
