### ISSUE TITLE
Error updating certificate

### ISSUE THREAD

**Issue by sdugan01** [vdenotaris/spring-boot-security-saml-sample#56]
sdugan$ sh ./update-certifcate.sh
depth=1 /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
verify return:0
DONE

**Comment by Weinrib** [comment]
Were you able to sort this out? I have the same issue.

**Comment by srinuydlp** [comment]
I have *.md file , I need to update certificate and signature, I got federationmetadata.xml from my provider, Please let me know how can I generate *.md file from federationmetadata.xml file

**Comment by chriswhite199** [comment]
@sdugan01 - You can ignore the error message relating to unable to get local issuer certificate

The `openssl s_client` line in `update-certificate.sh` could be replaced with the following to hide the error message if it really bothers you:

    keytool -printcert -rfc -sslserver $IDP_HOST:$IDP_PORT > $CERTIFICATE_FILE

**Comment by vdenotaris** [comment]
Thanks @chriswhite199 for your support.
