### ISSUE TITLE
org.opensaml.saml2.metadata.provider.MetadataProviderException: org.opensaml.saml2.metadata.provider.MetadataProviderException: Error retrieving metadata from https://idp.ssocircle.com/idp-meta.xml

### ISSUE THREAD

**Issue by kunudash** [vdenotaris/spring-boot-security-saml-sample#61]
I can access the URL https://idp.ssocircle.com/idp-meta.xml in my browser and access the xml but on server startup i see this exception in eclipse.

**org.opensaml.saml2.metadata.provider.MetadataProviderException: Error retrieving metadata from https://idp.ssocircle.com/idp-meta.xml
	at org.opensaml.saml2.metadata.provider.HTTPMetadataProvider.fetchMetadata(HTTPMetadataProvider.java:274) ~[opensaml-2.6.1.jar:?]
	at org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider.refresh(AbstractReloadingMetadataProvider.java:255) [opensaml-2.6.1.jar:?]**

Please help me . I am stuck. I want to test sso with this sample project with ssocircle.If this is working I have to use a different IDP.

**Comment by kunudash** [comment]
Do I need to generate samlKeystore.jks file using below command

keytool -import -alias ssocircle -file ssocircle.cert -keystore samlKeystore.jks -storepass nalle123 -noprompt

If yes then from where I can get thessocircle.cert file?

**Comment by vdenotaris** [comment]
Please read that: https://github.com/vdenotaris/spring-boot-security-saml-sample#additional-notes

**Comment by kunudash** [comment]
I have read those comments. I am ruuning in windows. Can you give commands to run in windows platform.
