### ISSUE TITLE
Update for Spring Boot 2

### ISSUE THREAD

**Issue by chriswhite199** [vdenotaris/spring-boot-security-saml-sample#62]
Feature Request: Update the dependencies to spring boot 2.x (2.0.5 at time of writing)

**Comment by chriswhite199** [comment]
This might be blocked as SAMLBootstrap imports BootstrapException, which is no longer part of spring-beans dependency in spring 5.x

**Comment by vdenotaris** [comment]
I did just release a new version, based on Spring Boot 2.1.1.RELEASE. 👍
