### ISSUE TITLE
issue with unit testing

### ISSUE THREAD

**Issue by ptanwar27** [vdenotaris/spring-boot-security-saml-sample#71]
**Describe the bug**
Thanks @vdenotaris for this example. It really helped me in implementing SAML with ADFS.
I am working on unit test part now. I try to use test cases present in your repo. 
For me it is not able to recognize  @WithMockUser bean used in SSOControllerTest and import 
import org.springframework.security.test.context.support.WithMockUser has compilation issues.
**To Reproduce**

 Using org.springframework.security:spring-security-test:5.1.5.RELEASE
org.springframework.security.extensions:spring-security-saml2-core:1.0.3.RELEASE
org.springframework:spring-test:5.1.2.RELEASE

Let me know if any other configs needed from my side.

**Comment by vdenotaris** [comment]
Hi @ptanwar27 

I am actually unable to reproduce your error.
Are you using this project as is or did u customize it?

In the first case, please check your Maven configuration properly.
In the second case, customizations fall out of this project scope and thus not supported.

**Comment by ptanwar27** [comment]
@vdenotaris Thanks for the response. I did customize it and able to test it. Thanks
