### ISSUE TITLE
Docker: javax.net.ssl.SSLPeerUnverifiedException: SSL peer failed hostname validation for name: null

### ISSUE THREAD

**Issue by zyhalj** [vdenotaris/spring-boot-security-saml-sample#73]
I try to pull your app image from the hub.docker.com and run it. But I get error 
javax.net.ssl.SSLPeerUnverifiedException: SSL peer failed hostname validation for name: null

I notice the readme file mentions to resolve this issue to call following command.
...
RUN cd /usr/src/app/src/main/resources/saml/ && sh ./update-certifcate.sh
..

I check your Dockerfile file, the command had been called.

 I'm not sure where is wrong now?

**Comment by vdenotaris** [comment]
Just fixed.

Thanks for your reporting.
