### ISSUE TITLE
Localhost redirect on first click regardless user's context

### ISSUE THREAD

**Issue by pcnoic** [vdenotaris/spring-boot-security-saml-sample#81]
**Description**
When booting the application, either as a container or natively on the host, if a user tries to visit the application URL from a third host, the redirection that occurs upon the "Get Started" button is redirecting him back to the third host's localhost.

**To Reproduce**
1. Boot the application either as a container or natively.
2. Navigate to the URL of the application from a second host.
3. Click on the "Get Started" button

**Expected behavior**
The redirect that is coming from the application, forcing the user's browser to visit the localhost regardless of the context of the runtime, should redirect him to the proper URL on the third host. 

**Desktop**
 - OS: Any
 - Browser: Tested with Safari, Chrome and Firefox.
 - Version: latest stable

**Proposed solution**
I was able to overcome the issue by editing the `th:href` link that was referenced in the "Get Started" button from `@{saml/login}` to `@{/saml/login}`. After the fix, I was not able to replicate the issue in either condition.

**Comment by vdenotaris** [comment]
Thanks for the reporting.
The issue has been fixed.
