### ISSUE TITLE
Browser back redirects to "/saml/SSO" page.

### ISSUE THREAD

**Issue by mcdperera** [vdenotaris/spring-boot-security-saml-sample#87]
Hi all,

When I run the test project, click the provider and logged to the provider's system. 

Provider redirect to the landing page (/landing) with the correct user name.

If I press browser back button twice sometimes page redirects to the "/saml/SSO" with following error appears.

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Nov 06 13:14:22 CST 2020
There was an unexpected error (type=None, status=999).
No message available
```

I testing Firefox Chrome and Safari and I got the same error. Error is not always appears.

**Comment by vdenotaris** [comment]
Expected behaviour.
