### ISSUE TITLE
Handle URL encoding in SAML response

### ISSUE THREAD

**Issue by minaksheej** [vdenotaris/spring-boot-security-saml-sample#88]
I am using spring-security-saml for SSO, its worked fine on my local system. While I have deployed it ,stopped working
I found the saml response that I am receiving on server is having having URL encoding over base64 encoded response
and while saml is decoding the response its giving error.

Is there any  configuration that I can enable to parse URL encoding on SAML response .
Please suggest a way to fix this problem.

**Comment by vdenotaris** [comment]
See: https://github.com/spring-projects/spring-security-saml/issues/248
